### ISSUE TITLE
`Language.is_valid` returns `True` for invalid tags

### ISSUE THREAD

**Issue by dscorbett** [rspeer/langcodes#46]
`is_valid` returns `True` for an invalid tag if all its subtags are prefixes of valid subtags.
```python-console
>>> Language.get('aaj').is_valid()
True
>>> Language.get('en-Latnx').is_valid()
True
```

**Comment by rspeer** [comment]
Oh, wow. Thanks for finding that, and I'll work on it.

**Comment by rspeer** [comment]
Fixed in master, and I'll release it soon.
