### ISSUE TITLE
Tags with singletons not followed by extensions should be rejected

### ISSUE THREAD

**Issue by dscorbett** [rspeer/langcodes#49]
A singleton must be followed by at least one extension subtag for a tag to be well-formed. This library correctly detects ill-formed tags like `und-a` but misses the case where the singleton is not the final subtag. It should throw a `LanguageTagError`.
```python-console
>>> Language.get('und-a-b-xyz')
Language.make(extensions=['a', 'b-xyz'])
```

**Comment by rspeer** [comment]
Fixed in master.
