### ISSUE TITLE
No wheel in the package on pypi when using pip installl

### ISSUE THREAD

**Issue by covuworie** [rspeer/langcodes#54]
Hi, I just did tried to do a pip install of the package using the `--only-binary :all:` flag described in the [pip documentation](https://pip.pypa.io/en/stable/cli/pip_install/#cmdoption-only-binary).

It failed with the following error.

```
ERROR: Could not find a version that satisfies the requirement langcodes[data]<4.0.0,>=3.1.0
ERROR: No matching distribution found for langcodes[data]<4.0.0,>=3.1.0
```

Then I went to the package in pypi and found that there is only a source distribution there and no built wheel. I expected there to be a wheel as it is standard in python packaging.

**Comment by rspeer** [comment]
Fixed in version 3.3 because I switched the build system to Poetry.
