### ISSUE TITLE
missing `language_data` dependency after `pip install langcodes`

### ISSUE THREAD

**Issue by reynoldsnlp** [rspeer/langcodes#58]
Please add this dependency to setup.cfg or setup.py.

**Comment by cdleong** [comment]
@reynoldsnlp but it's not a dependency, I believe? It's an optional package that doesn't _have_ to be installed for langcodes to work.

**Comment by cdleong** [comment]
In the README it says: 
> Moved bulky data, particularly language names, into a separate language_data package. In situations where the data isn't needed, langcodes becomes a smaller, pure-Python package with no dependencies.
